# Generated by Django 2.1.3 on 2020-09-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='clothe',
            name='fabric',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.Fabric'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.Size'),
        ),
    ]
