# Generated by Django 2.1.3 on 2020-09-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='name',
            new_name='fabric',
        ),
        migrations.AlterField(
            model_name='size',
            name='length',
            field=models.CharField(max_length=200),
        ),
    ]
